Machine Learning (ML) is a branch of Artificial Intelligence that enables computers to learn from data and improve their performance without being explicitly programmed for every task.

### Machine learning 
* Machine Learning is a method of teaching computers to learn from data and improve their performance automatically.


| Type                     | Description                          |
| ------------------------ | ------------------------------------ |
| Supervised Learning      | Learns from labeled data             |
| Unsupervised Learning    | Learns from unlabeled data           |
| Semi-Supervised Learning | Uses both labeled and unlabeled data |
| Reinforcement Learning   | Learns through rewards and penalties |

| Labeled Data                 | Unlabeled Data                   |
| ---------------------------- | -------------------------------- |
| Has correct answers (labels) | No correct answers               |
| Used in Supervised Learning  | Used in Unsupervised Learning    |
| Easier to train models       | Used to discover hidden patterns |
| Example: House Price Dataset | Example: Customer Purchase Data  |

In [32]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR

In [33]:
df = pd.read_csv(r'D:\Data Science with AI & ML\SITP-12th-May\MACHINE LEARNING\PROJECT 2\DATA\Clean_bike_data.csv')

In [34]:
df

,Unnamed: 0,price,kms_driven,owner,age,power,brand
0,0,35000.0,17654.0,First Owner,3.0,110.0,TVS
1,1,119900.0,11000.0,First Owner,4.0,350.0,Royal Enfield
2,2,600000.0,110.0,First Owner,8.0,675.0,Triumph
3,3,65000.0,16329.0,First Owner,4.0,180.0,TVS
4,4,80000.0,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
7301,9362,25000.0,48587.0,First Owner,8.0,150.0,Hero
7302,9369,35000.0,60000.0,First Owner,9.0,220.0,Bajaj
7303,9370,450000.0,3430.0,First Owner,4.0,750.0,Harley-Davidson
7304,9371,139000.0,21300.0,First Owner,4.0,400.0,Bajaj
7305,9372,80000.0,7127.0,First Owner,5.0,220.0,Bajaj

In [35]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [36]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
7301   25000.0     48587.0  First Owner  8.0  150.0             Hero
7302   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
7303  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
7304  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
7305   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [37]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [38]:
dct_owner={'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
df['owner']=df['owner'].map(dct_owner)

In [39]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
7301   25000.0     48587.0      1  8.0  150.0             Hero
7302   35000.0     60000.0      1  9.0  220.0            Bajaj
7303  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
7304  139000.0     21300.0      1  4.0  400.0            Bajaj
7305   80000.0      7127.0      1  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [40]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}
df['brand']=df['brand'].map(brand_dict)

In [41]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
7301   25000.0     48587.0      1  8.0  150.0      6
7302   35000.0     60000.0      1  9.0  220.0      7
7303  450000.0      3430.0      1  4.0  750.0     15
7304  139000.0     21300.0      1  4.0  400.0      7
7305   80000.0      7127.0      1  5.0  220.0      7

[7306 rows x 6 columns]

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [44]:
x=df.drop("price",axis=1)
y=df[['price']]

In [45]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7301     48587.0      1  8.0  150.0      6
7302     60000.0      1  9.0  220.0      7
7303      3430.0      1  4.0  750.0     15
7304     21300.0      1  4.0  400.0      7
7305      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [46]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [47]:
# x_train, y_train, x_test, y_test=train_test_split(x, y, random_state=42, test_size=0.2)
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((5844, 5), (5844, 1), (1462, 5), (1462, 1))

In [48]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')

In [49]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [50]:
y_pred =dtc.predict(x_test)

In [51]:
dtc.predict([[16329.0,  1,  4.0,  180.0,  1]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([65000.])

In [52]:
print(dtc.score(x_train, y_train))
print(dtc.score(x_test, y_test))

0.9493497604380561
0.038303693570451436

In [53]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [54]:
# lr = LinearRegression()
# lr.fit(x_train, y_train)

In [55]:
from sklearn.ensemble import RandomForestRegressor
lr=RandomForestRegressor()
lr.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [56]:
bike_1 =lr.predict([[17654.0,  1,  3.0,  110.0,  1]])
bike_1

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([38328.])

In [57]:
print(lr.score(x_train, y_train))
print(lr.score(x_test, y_test))

0.9857744149481672
0.8753945262356547

In [58]:
print(x_train.shape)
print(y_train.shape)

(5844, 5)
(5844, 1)

In [59]:
lr=SVR()
lr.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [60]:
print(lr.score(x_train, y_train))
print(lr.score(x_test, y_test))

-0.06164747200042009
-0.05789256698689371

In [61]:
import joblib
joblib.dump(lr, "model_rfr.lb")

['model_rfr.lb']

In [62]:
model=joblib.load('model.lb')

FileNotFoundError: [Errno 2] No such file or directory: 'model.lb'

In [ ]:
model.predict([[11000.0,  1,  4.0,  350.0,  2]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([54848.42236715])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(645, 645))

In [ ]:
from sklearn.metrics import confusion_matrix
y_true = y_test["price"]
y_test_class = (y_true > y_true.mean()).astype(int)
y_pred_class = (y_pred > y_true.mean()).astype(int)
confusion_matrix(y_test_class, y_pred_class)

array([[935,  52],
       [ 73, 402]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

      5000.0       0.00      0.00      0.00         1
      6700.0       0.00      0.00      0.00         1
      6890.0       0.00      0.00      0.00         0
      8000.0       0.00      0.00      0.00         0
      8100.0       0.00      0.00      0.00         1
      9000.0       0.00      0.00      0.00         1
     10000.0       0.00      0.00      0.00         2
     10005.0       0.00      0.00      0.00         1
     10414.0       0.00      0.00      0.00         1
     10500.0       0.00      0.00      0.00         2
     10600.0       0.00      0.00      0.00         1
     10800.0       0.00      0.00      0.00         1
     11000.0       0.00      0.00      0.00         3
     11400.0       0.00      0.00      0.00         1
     11900.0       0.00      0.00      0.00         1
     12000.0       0.14      0.20      0.17         5
     12200.0       0.00      0.00      0.00         0
     13000.0       0.00      0.00      0.00         5
     13200.0       0.00      0.00      0.00         0
     13500.0       0.00      0.00      0.00         3
     13700.0       0.00      0.00      0.00         2
     14000.0       0.00      0.00      0.00         6
     14500.0       0.00      0.00      0.00         2
     14700.0       0.00      0.00      0.00         0
     14800.0       0.00      0.00      0.00         1
     15000.0       0.06      0.12      0.08         8
     15300.0       0.00      0.00      0.00         0
     15500.0       0.00      0.00      0.00         2
     15600.0       0.00      0.00      0.00         1
     15800.0       0.00      0.00      0.00         1
     15995.0       0.00      0.00      0.00         0
     16000.0       0.33      0.15      0.21        13
     16100.0       0.00      0.00      0.00         0
     16500.0       0.00      0.00      0.00         0
     16580.0       0.00      0.00      0.00         0
     16600.0       0.00      0.00      0.00         1
     16800.0       0.00      0.00      0.00         1
     16900.0       0.00      0.00      0.00         1
     17000.0       0.00      0.00      0.00        10
     17200.0       0.00      0.00      0.00         0
     17300.0       0.00      0.00      0.00         1
     17500.0       0.00      0.00      0.00         3
     17800.0       0.00      0.00      0.00         1
     18000.0       0.07      0.09      0.08        11
     18158.0       0.00      0.00      0.00         1
     18500.0       0.00      0.00      0.00         2
     18600.0       0.00      0.00      0.00         2
     18700.0       0.00      0.00      0.00         1
     18800.0       0.00      0.00      0.00         1
     18900.0       0.00      0.00      0.00         0
     19000.0       0.11      0.06      0.08        16
     19400.0       0.00      0.00      0.00         0
     19500.0       0.00      0.00      0.00         2
     19784.0       0.00      0.00      0.00         0
     19900.0       0.00      0.00      0.00         1
     20000.0       0.06      0.03      0.04        29
     20100.0       0.00      0.00      0.00         1
     20300.0       0.00      0.00      0.00         1
     20400.0       0.00      0.00      0.00         1
     20500.0       0.00      0.00      0.00         2
     20600.0       0.00      0.00      0.00         0
     20700.0       0.00      0.00      0.00         0
     20800.0       0.00      0.00      0.00         2
     21000.0       0.09      0.07      0.08        14
     21100.0       0.00      0.00      0.00         0
     21101.0       0.00      0.00      0.00         0
     21400.0       0.00      0.00      0.00         0
     21500.0       0.00      0.00      0.00         2
     21700.0       0.00      0.00      0.00         1
     21800.0       0.00      0.00      0.00         1
     21900.0       0.00      0.00      0.00         0
     22000.0       0.00      0.00      0.00        17
     22100.0       0.00      0.00      0.00         0
     22300.0       0.00      0.00      0.00         1
     22345.0       0.00      0.00      0.00         1
     22500.0       0.00      0.00      0.00         4
     22600.0       0.00      0.00      0.00         0
     22800.0       0.00      0.00      0.00         2
     22999.0       0.00      0.00      0.00         1
     23000.0       0.00      0.00      0.00        15
     23200.0       0.00      0.00      0.00         1
     23400.0       0.00      0.00      0.00         1
     23484.0       0.00      0.00      0.00         0
     23500.0       0.00      0.00      0.00         1
     23600.0       0.00      0.00      0.00         1
     23698.0       0.00      0.00      0.00         1
     24000.0       0.14      0.17      0.15        12
     24500.0       0.00      0.00      0.00         4
     24800.0       0.00      0.00      0.00         1
     24999.0       0.00      0.00      0.00         1
     25000.0       0.05      0.05      0.05        38
     25100.0       0.00      0.00      0.00         0
     25500.0       0.00      0.00      0.00         4
     25600.0       0.00      0.00      0.00         0
     25999.0       0.00      0.00      0.00         1
     26000.0       0.08      0.09      0.09        11
     26200.0       0.00      0.00      0.00         1
     26500.0       0.00      0.00      0.00         4
     26900.0       0.00      0.00      0.00         1
     27000.0       0.10      0.17      0.12         6
     27500.0       0.00      0.00      0.00         5
     28000.0       0.00      0.00      0.00        13
     28100.0       0.00      0.00      0.00         0
     28500.0       0.00      0.00      0.00         1
     28950.0       0.00      0.00      0.00         1
     28980.0       0.00      0.00      0.00         0
     29000.0       0.00      0.00      0.00         4
     29500.0       0.00      0.00      0.00         1
     29700.0       0.00      0.00      0.00         1
     29900.0       0.00      0.00      0.00         2
     29999.0       0.00      0.00      0.00         1
     30000.0       0.09      0.06      0.07        32
     30009.0       0.00      0.00      0.00         1
     30100.0       0.00      0.00      0.00         1
     30500.0       0.00      0.00      0.00         0
     30900.0       0.00      0.00      0.00         0
     31000.0       0.00      0.00      0.00         5
     31074.0       0.00      0.00      0.00         0
     31100.0       0.00      0.00      0.00         1
     31160.0       0.00      0.00      0.00         0
     31500.0       0.00      0.00      0.00         2
     31599.0       0.00      0.00      0.00         1
     31621.0       0.00      0.00      0.00         0
     31900.0       0.00      0.00      0.00         0
     32000.0       0.08      0.12      0.10        17
     32400.0       0.00      0.00      0.00         0
     32500.0       0.00      0.00      0.00         1
     32600.0       0.00      0.00      0.00         1
     32713.0       0.00      0.00      0.00         0
     32999.0       0.00      0.00      0.00         0
     33000.0       0.00      0.00      0.00        13
     33085.0       0.00      0.00      0.00         1
     33200.0       0.00      0.00      0.00         0
     33400.0       0.00      0.00      0.00         1
     33680.0       0.00      0.00      0.00         0
     33800.0       0.00      0.00      0.00         0
     34000.0       0.00      0.00      0.00         8
     34500.0       0.00      0.00      0.00         4
     34850.0       0.00      0.00      0.00         0
     34999.0       0.00      0.00      0.00         0
     35000.0       0.03      0.02      0.03        41
     35100.0       0.00      0.00      0.00         1
     35300.0       0.00      0.00      0.00         1
     35500.0       0.00      0.00      0.00         1
     35526.0       0.00      0.00      0.00         0
     35600.0       0.00      0.00      0.00         1
     35800.0       0.00      0.00      0.00         1
     35900.0       0.00      0.00      0.00         1
     35999.0       0.00      0.00      0.00         1
     36000.0       0.15      0.14      0.15        14
     36300.0       0.00      0.00      0.00         0
     36500.0       0.00      0.00      0.00         0
     36600.0       0.00      0.00      0.00         1
     36700.0       0.00      0.00      0.00         1
     37000.0       0.00      0.00      0.00         6
     37300.0       0.00      0.00      0.00         0
     37500.0       0.00      0.00      0.00         1
     37800.0       0.00      0.00      0.00         1
     38000.0       0.09      0.07      0.08        15
     38500.0       0.00      0.00      0.00         2
     38800.0       0.00      0.00      0.00         0
     39000.0       0.00      0.00      0.00         7
     39200.0       0.00      0.00      0.00         0
     39500.0       0.00      0.00      0.00         1
     39700.0       0.00      0.00      0.00         0
     39999.0       0.00      0.00      0.00         1
     40000.0       0.12      0.08      0.10        25
     40100.0       0.00      0.00      0.00         1
     40200.0       0.00      0.00      0.00         0
     40300.0       0.00      0.00      0.00         1
     40500.0       0.00      0.00      0.00         1
     40800.0       0.00      0.00      0.00         0
     40900.0       0.00      0.00      0.00         0
     41000.0       0.00      0.00      0.00        10
     41245.0       0.00      0.00      0.00         0
     41400.0       0.00      0.00      0.00         1
     42000.0       0.08      0.05      0.06        20
     42200.0       0.00      0.00      0.00         0
     42400.0       0.00      0.00      0.00         0
     42500.0       0.00      0.00      0.00         1
     42700.0       0.00      0.00      0.00         1
     42985.0       0.00      0.00      0.00         1
     43000.0       0.00      0.00      0.00         8
     43300.0       0.00      0.00      0.00         1
     43500.0       0.00      0.00      0.00         1
     43800.0       0.00      0.00      0.00         1
     43959.0       0.00      0.00      0.00         1
     44000.0       0.00      0.00      0.00         6
     44400.0       0.00      0.00      0.00         1
     45000.0       0.07      0.08      0.08        24
     45400.0       0.00      0.00      0.00         2
     45500.0       0.00      0.00      0.00         0
     45600.0       0.00      0.00      0.00         1
     45636.0       0.00      0.00      0.00         0
     45801.0       0.00      0.00      0.00         1
     45900.0       0.00      0.00      0.00         2
     45918.0       0.00      0.00      0.00         1
     46000.0       0.00      0.00      0.00         2
     46200.0       0.00      0.00      0.00         0
     46300.0       0.00      0.00      0.00         1
     46500.0       0.00      0.00      0.00         4
     46800.0       0.00      0.00      0.00         0
     46900.0       0.00      0.00      0.00         1
     47000.0       0.00      0.00      0.00         9
     47167.0       0.00      0.00      0.00         0
     47500.0       0.00      0.00      0.00         3
     47600.0       0.00      0.00      0.00         0
     47800.0       0.00      0.00      0.00         1
     48000.0       0.08      0.09      0.09        11
     48300.0       0.00      0.00      0.00         0
     48400.0       0.00      0.00      0.00         1
     48500.0       0.00      0.00      0.00         0
     48900.0       0.00      0.00      0.00         0
     48915.0       0.00      0.00      0.00         1
     48928.0       0.00      0.00      0.00         0
     49000.0       0.00      0.00      0.00         5
     49500.0       0.00      0.00      0.00         1
     49990.0       0.00      0.00      0.00         0
     50000.0       0.00      0.00      0.00        20
     50001.0       0.00      0.00      0.00         1
     50100.0       0.00      0.00      0.00         0
     50200.0       0.00      0.00      0.00         0
     50400.0       0.00      0.00      0.00         1
     50700.0       0.00      0.00      0.00         0
     50900.0       0.00      0.00      0.00         1
     51000.0       0.00      0.00      0.00         4
     51500.0       0.00      0.00      0.00         1
     51715.0       0.00      0.00      0.00         0
     51900.0       0.00      0.00      0.00         0
     52000.0       0.14      0.08      0.11        12
     52200.0       0.00      0.00      0.00         0
     53000.0       0.00      0.00      0.00         3
     53300.0       0.00      0.00      0.00         1
     54000.0       0.00      0.00      0.00         1
     54200.0       0.00      0.00      0.00         0
     54400.0       0.00      0.00      0.00         0
     54500.0       0.00      0.00      0.00         0
     54799.0       0.00      0.00      0.00         0
     54800.0       0.00      0.00      0.00         0
     54900.0       0.00      0.00      0.00         1
     55000.0       0.11      0.13      0.12        23
     55200.0       0.00      0.00      0.00         1
     55400.0       0.00      0.00      0.00         0
     55500.0       0.00      0.00      0.00         1
     56000.0       0.00      0.00      0.00         6
     56500.0       0.00      0.00      0.00         2
     56789.0       0.00      0.00      0.00         0
     56800.0       0.00      0.00      0.00         1
     57000.0       0.00      0.00      0.00         5
     57500.0       0.00      0.00      0.00         0
     57800.0       0.00      0.00      0.00         1
     58000.0       0.00      0.00      0.00         8
     58100.0       0.00      0.00      0.00         1
     58416.0       0.00      0.00      0.00         1
     58600.0       0.00      0.00      0.00         1
     58690.0       0.00      0.00      0.00         0
     58742.0       0.00      0.00      0.00         1
     59000.0       0.00      0.00      0.00         2
     59300.0       0.00      0.00      0.00         1
     59999.0       0.00      0.00      0.00         1
     60000.0       0.08      0.10      0.09        21
     60311.0       0.00      0.00      0.00         0
     60350.0       0.00      0.00      0.00         0
     61000.0       0.00      0.00      0.00         1
     61200.0       0.00      0.00      0.00         1
     61400.0       0.00      0.00      0.00         0
     61483.0       0.00      0.00      0.00         1
     61700.0       0.00      0.00      0.00         1
     62000.0       0.00      0.00      0.00         6
     62400.0       0.00      0.00      0.00         0
     62500.0       0.00      0.00      0.00         0
     63000.0       0.00      0.00      0.00         3
     63400.0       0.00      0.00      0.00         0
     63499.0       0.00      0.00      0.00         0
     63647.0       0.00      0.00      0.00         0
     63700.0       0.00      0.00      0.00         0
     64999.0       0.00      0.00      0.00         0
     65000.0       0.00      0.00      0.00        25
     65200.0       0.00      0.00      0.00         1
     65800.0       0.00      0.00      0.00         0
     65949.0       0.00      0.00      0.00         0
     66000.0       0.00      0.00      0.00         5
     66400.0       0.00      0.00      0.00         1
     66700.0       0.00      0.00      0.00         0
     66800.0       0.00      0.00      0.00         0
     67000.0       0.00      0.00      0.00         3
     67100.0       0.00      0.00      0.00         1
     67300.0       0.00      0.00      0.00         1
     67500.0       0.00      0.00      0.00         1
     67800.0       0.00      0.00      0.00         0
     68000.0       0.00      0.00      0.00         7
     68500.0       0.00      0.00      0.00         0
     68700.0       0.00      0.00      0.00         0
     68900.0       0.00      0.00      0.00         1
     69000.0       0.00      0.00      0.00         2
     69500.0       0.00      0.00      0.00         2
     69600.0       0.00      0.00      0.00         0
     70000.0       0.00      0.00      0.00        20
     70300.0       0.00      0.00      0.00         1
     70400.0       0.00      0.00      0.00         1
     70500.0       0.00      0.00      0.00         0
     70705.0       0.00      0.00      0.00         1
     71000.0       0.00      0.00      0.00         2
     71299.0       0.00      0.00      0.00         0
     71300.0       0.00      0.00      0.00         1
     71400.0       0.00      0.00      0.00         1
     72000.0       0.00      0.00      0.00         4
     72300.0       0.00      0.00      0.00         0
     72500.0       0.00      0.00      0.00         2
     73000.0       0.00      0.00      0.00         1
     73500.0       0.00      0.00      0.00         1
     73800.0       0.00      0.00      0.00         1
     74000.0       0.00      0.00      0.00         3
     74200.0       0.00      0.00      0.00         1
     74400.0       0.00      0.00      0.00         1
     74500.0       0.00      0.00      0.00         0
     75000.0       0.00      0.00      0.00        18
     75200.0       0.00      0.00      0.00         1
     75500.0       0.00      0.00      0.00         1
     75700.0       0.00      0.00      0.00         1
     76000.0       0.00      0.00      0.00         2
     76200.0       0.00      0.00      0.00         1
     77000.0       0.00      0.00      0.00         2
     77100.0       0.00      0.00      0.00         0
     78000.0       0.00      0.00      0.00         5
     78500.0       0.00      0.00      0.00         3
     79000.0       0.00      0.00      0.00         1
     79450.0       0.00      0.00      0.00         0
     79900.0       0.00      0.00      0.00         1
     80000.0       0.13      0.09      0.11        22
     80999.0       0.00      0.00      0.00         1
     81000.0       0.00      0.00      0.00         1
     81100.0       0.00      0.00      0.00         1
     82000.0       0.00      0.00      0.00         4
     82400.0       0.00      0.00      0.00         0
     82500.0       0.00      0.00      0.00         0
     82800.0       0.00      0.00      0.00         0
     83000.0       0.00      0.00      0.00         2
     83100.0       0.00      0.00      0.00         0
     84000.0       0.00      0.00      0.00         2
     84100.0       0.00      0.00      0.00         1
     84200.0       0.00      0.00      0.00         0
     84800.0       0.00      0.00      0.00         1
     84999.0       0.00      0.00      0.00         0
     85000.0       0.00      0.00      0.00        10
     85500.0       0.00      0.00      0.00         1
     85990.0       0.00      0.00      0.00         0
     85999.0       0.00      0.00      0.00         1
     86000.0       0.00      0.00      0.00         2
     86900.0       0.00      0.00      0.00         0
     87000.0       0.00      0.00      0.00         2
     87500.0       0.00      0.00      0.00         0
     88000.0       0.00      0.00      0.00         7
     89000.0       0.00      0.00      0.00         3
     89025.0       0.00      0.00      0.00         0
     89135.0       0.00      0.00      0.00         1
     89600.0       0.00      0.00      0.00         0
     89700.0       0.00      0.00      0.00         2
     89900.0       0.00      0.00      0.00         0
     90000.0       0.00      0.00      0.00        15
     90100.0       0.00      0.00      0.00         0
     90595.0       0.00      0.00      0.00         0
     91000.0       0.00      0.00      0.00         2
     91400.0       0.00      0.00      0.00         1
     91500.0       0.00      0.00      0.00         1
     92000.0       0.00      0.00      0.00         1
     92200.0       0.00      0.00      0.00         0
     92500.0       0.00      0.00      0.00         1
     93000.0       0.00      0.00      0.00         2

In [ ]:
#  MSE
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)

4075279688.480164

In [63]:
# MSE & MAE
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("Mean_squared_error:-",mean_squared_error(y_test, y_pred))
print("Mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

Mean_squared_error:- 4092397008.290014
Mean_absolute_error:- 20110.61149110807

In [64]:
rmse=np.sqrt(mean_squared_error(y_test, y_pred))

In [65]:
rmse

np.float64(63971.84543445666)

In [66]:
rmse=np.sqrt(mean_absolute_error(y_test, y_pred))

In [67]:
rmse

np.float64(141.81188769319752)

In [68]:
from sklearn.neighbors import KNeighborsClassifier
knn =KNeighborsClassifier()
knn.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [69]:
pred =knn.predict(x_test)

In [70]:
pred

array([ 22000.,  90000.,  13500., ...,  90000., 130000.,  66000.],
      shape=(1462,))

In [71]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [72]:
knn.score(x_test, y_test)

0.01709986320109439

In [73]:
knn.score(x_train, y_train)

0.21697467488021902

In [74]:
# without hyper parameter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier()
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [75]:
rfc.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [76]:
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

0.03488372093023256
0.9493497604380561

In [77]:
# With hyper paramter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=1, min_samples_split=2)
rfc.fit(x_train, y_train)
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.03556771545827633
0.04140999315537303