In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR

In [3]:
df = pd.read_csv('Sales_clean_data.csv')

In [4]:
df

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02
99,665095412,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [5]:
df.head()

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       100 non-null    int64
 1   units_sold     100 non-null    int64
 2   unit_price     100 non-null    float64
 3   unit_cost      100 non-null    float64
 4   total_revenue  100 non-null    float64
 5   total_cost     100 non-null    float64
 6   total_profit   100 non-null    float64
dtypes: float64(5), int64(2)
memory usage: 5.6 KB

In [7]:
if 'order_date' not in df.columns:
    df['order_date'] = np.random.randint(1, 31, size=len(df))

In [8]:
df

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,order_date
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50,24
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36,25
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75,19
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82,2
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50,3
...,...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72,23
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47,10
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05,24
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02,10
99,665095412,5367,668.27,502.54,3586605.09,2697132.18,889472.91,4

In [9]:
x=df.drop("order_date", axis=1)

In [10]:
y=df[['order_date']]

In [11]:
x

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02
99,665095412,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [12]:
y

    order_date
0           24
1           25
2           19
3            2
4            3
..         ...
95          23
96          10
97          24
98          10
99           4

[100 rows x 1 columns]

In [13]:
y['order_date'].unique()

array([24, 25, 19,  2,  3,  7, 27, 28,  5,  9,  8, 13, 29, 23, 12, 18, 21,
       15, 30, 17, 20, 10,  6,  1, 16, 26, 22, 14, 11,  4], dtype=int32)

In [14]:
y['order_date'].value_counts()

order_date
24    6
2     6
25    5
3     5
7     5
28    5
13    5
21    5
30    5
9     4
23    4
12    4
18    4
15    4
10    4
22    4
19    3
27    3
8     3
29    3
16    2
26    2
4     2
5     1
17    1
20    1
6     1
1     1
14    1
11    1
Name: count, dtype: int64

In [15]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((80, 7), (80, 1), (20, 7), (20, 1))

In [16]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')

In [17]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [18]:
y_pred = dtc.predict(x_test)
y_pred[:10]

array([18, 30, 21,  7, 28, 27,  8,  3,  3, 22], dtype=int32)

In [19]:
dtc.predict([[115456712,  5062,  651.21,  524.96,  3296425.02,  2657347.52,  639077.50]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([3], dtype=int32)

In [20]:
print("Train Score:", dtc.score(x_train, y_train))
print("Test Score:", dtc.score(x_test, y_test))

Train Score: 1.0
Test Score: 0.1

In [21]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': 42,
 'splitter': 'best'}

In [22]:
sm=LinearRegression()

In [23]:
sm.fit(x_train, y_train)

LinearRegression()

In [24]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

0.01591553071392815
-0.08202230552272227

In [25]:
import joblib
joblib.dump(sm, "model.lb")

['model.lb']

In [26]:
model=joblib.load('model.lb')

In [27]:
model.predict([[512878119,  888,  109.28,  35.84,  97040.64,  31825.92,  65214.72]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[17.57313539]])

In [28]:
sm=SVC()
sm.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [29]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

0.0875
0.05

In [30]:
sm=SVR()
sm.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [31]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

-0.007635654352451615
0.012496774213838657

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [33]:
print(y_test.iloc[:, 0].unique())

[26 30 11  9  6  3 18  2  5 24 28 19 16 13 22 27]

In [34]:
print(len(y_test.iloc[:,0].unique()))

16

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test.iloc[:,0], y_pred))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       0.33      0.50      0.40         2
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         3
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         0
          30       1.00      0.50      0.67         2

    accuracy                           0.10        20
   macro avg       0.06      0.05      0.05        20
weighted avg       0.13      0.10      0.11        20

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [36]:
y_binary = (df['order_date'] > 15).astype(int)
x_train_b, x_test_b, y_train_b, y_test_b = train_test_split(
    x, y_binary, test_size=0.2, random_state=42 )
dtc_b = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc_b.fit(x_train_b, y_train_b)
y_pred_b = dtc_b.predict(x_test_b)

In [37]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test_b, y_pred_b)
print(cm)
print("\nClassification Report:\n")
print(classification_report(y_test_b, y_pred_b))

[[2 6]
 [5 7]]

Classification Report:

              precision    recall  f1-score   support

           0       0.29      0.25      0.27         8
           1       0.54      0.58      0.56        12

    accuracy                           0.45        20
   macro avg       0.41      0.42      0.41        20
weighted avg       0.44      0.45      0.44        20

In [38]:
#  MSE
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)

127.65

In [39]:
# MSE & MAE
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("Mean_squared_error:-",mean_squared_error(y_test, y_pred))
print("Mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

Mean_squared_error:- 127.65
Mean_absolute_error:- 8.15

In [40]:
rmse=np.sqrt(mean_squared_error(y_test, y_pred))

In [41]:
rmse

np.float64(11.298229949863828)

In [42]:
rmse=np.sqrt(mean_absolute_error(y_test, y_pred))

In [43]:
rmse

np.float64(2.8548204847240397)