In [134]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR

In [135]:
df = pd.read_csv(r'D:\Data Science with AI & ML\SITP-12th-May\MACHINE LEARNING\PROJECT 1\DATA\Clean_laptop_price_prediction_data1.csv')

In [136]:
df

,Unnamed: 0,brand,price,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,1,49900,0,0,1,0,1,1,0,15.6,1920.0,1080.0,1,1
1,1,1,39900,1,1,1,0,1,1,1,15.6,1920.0,1080.0,1,1
2,2,2,26990,2,2,1,0,1,1,2,14.0,1920.0,1080.0,1,1
3,3,3,59729,3,3,2,1,1,1,3,14.0,2240.0,1400.0,1,1
4,4,4,69990,4,4,1,0,2,1,4,13.3,2560.0,1600.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,888,6,44990,183,1,1,0,1,1,63,15.6,1920.0,1080.0,1,1
883,889,6,110000,54,11,2,11,5,1,77,15.6,2560.0,1440.0,12,1
884,890,6,189990,152,11,4,2,5,1,28,14.0,2560.0,1600.0,1,1
885,891,6,129990,87,10,2,0,1,1,5,15.6,1920.0,1080.0,1,1
886,892,6,131990,152,11,2,0,5,1,5,15.6,1920.0,1080.0,1,1

In [137]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [138]:
df.drop(["resolution_width",  "resolution_height"], axis=1, inplace=True)

In [139]:
df

,brand,price,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,OS,warranty
0,1,49900,0,0,1,0,1,1,0,15.6,1,1
1,1,39900,1,1,1,0,1,1,1,15.6,1,1
2,2,26990,2,2,1,0,1,1,2,14.0,1,1
3,3,59729,3,3,2,1,1,1,3,14.0,1,1
4,4,69990,4,4,1,0,2,1,4,13.3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
882,6,44990,183,1,1,0,1,1,63,15.6,1,1
883,6,110000,54,11,2,11,5,1,77,15.6,12,1
884,6,189990,152,11,4,2,5,1,28,14.0,1,1
885,6,129990,87,10,2,0,1,1,5,15.6,1,1
886,6,131990,152,11,2,0,5,1,5,15.6,1,1

In [140]:
df.duplicated().sum()

np.int64(0)

In [141]:
df.isnull().sum()

brand           0
price           0
processor       0
CPU             0
Ram             0
Ram_type        0
ROM             0
ROM_type        0
GPU             0
display_size    0
OS              0
warranty        0
dtype: int64

In [142]:
x=df.drop('price', axis=1)

In [143]:
y=df[['price']]

In [144]:
y

      price
0     49900
1     39900
2     26990
3     59729
4     69990
..      ...
882   44990
883  110000
884  189990
885  129990
886  131990

[887 rows x 1 columns]

In [145]:
x

,brand,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,OS,warranty
0,1,0,0,1,0,1,1,0,15.6,1,1
1,1,1,1,1,0,1,1,1,15.6,1,1
2,2,2,2,1,0,1,1,2,14.0,1,1
3,3,3,3,2,1,1,1,3,14.0,1,1
4,4,4,4,1,0,2,1,4,13.3,2,1
...,...,...,...,...,...,...,...,...,...,...,...
882,6,183,1,1,0,1,1,63,15.6,1,1
883,6,54,11,2,11,5,1,77,15.6,12,1
884,6,152,11,4,2,5,1,28,14.0,1,1
885,6,87,10,2,0,1,1,5,15.6,1,1
886,6,152,11,2,0,5,1,5,15.6,1,1

In [146]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((709, 11), (709, 1), (178, 11), (178, 1))

In [147]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')

In [148]:
dtc.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)

DecisionTreeClassifier(criterion='entropy')

In [149]:
y_pred =dtc.predict(x_test)

In [150]:
dtc.predict([[2,  2,  2,  1,  0,  1,  1,  2,  14.0,  1,  1]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([26990])

In [151]:
print(dtc.score(x_train, y_train))
print(dtc.score(x_test, y_test))

0.8688293370944993
0.011235955056179775

In [152]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [153]:
# laptop_lr=LinearRegression()
# laptop_lr.fit(x_train, y_train)

In [154]:
from sklearn.ensemble import RandomForestRegressor
laptop_lr=RandomForestRegressor()
laptop_lr.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [155]:
print(laptop_lr.score(x_train, y_train))
print(laptop_lr.score(x_test, y_test))

0.9612184124676675
0.7490280732078366

In [156]:
print(x_train.shape)
print(y_train.shape)

(709, 11)
(709, 1)

In [157]:
from sklearn.ensemble import RandomForestRegressor
import joblib

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(x_train, y_train.values.ravel())

joblib.dump(laptop_lr,"model_rfr.lb")

['model_rfr.lb']

In [158]:
# laptop_lr=SVR()
# laptop_lr.fit(x_train, y_train)

In [159]:
print(laptop_lr.score(x_train, y_train))
print(laptop_lr.score(x_test, y_test))

0.9612184124676675
0.7490280732078366

In [160]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((709, 11), (709, 1), (178, 11), (178, 1))

In [161]:
print(x_train.shape)
print(y_train.shape)

(709, 11)
(709, 1)

In [162]:
# import joblib
# joblib.dump(laptop_lr, "model_rfr.lb")

In [163]:
model=joblib.load('model_rfr.lb')

In [164]:
model.predict([[1,  1,  1,  1,  0,  1,  1,  1,  15.6,  1,  1]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([42006.40491714])

In [165]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], shape=(213, 213))

In [166]:
print(len(y_test.iloc[:,0].unique()))

129

In [167]:
from sklearn.metrics import confusion_matrix
y_true = y_test.values.ravel()
y_test_class = (y_true > y_true.mean()).astype(int)
y_pred_class = (y_pred > y_true.mean()).astype(int)
cm = confusion_matrix(y_test_class, y_pred_class)

cm

array([[111,   9],
       [ 15,  43]])

In [168]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       10990       0.00      0.00      0.00         1
       12990       0.00      0.00      0.00         1
       15990       0.00      0.00      0.00         0
       16990       0.00      0.00      0.00         1
       17990       0.00      0.00      0.00         1
       18990       0.00      0.00      0.00         0
       21990       0.00      0.00      0.00         1
       23990       0.00      0.00      0.00         1
       24999       0.00      0.00      0.00         0
       25449       0.00      0.00      0.00         1
       25990       0.00      0.00      0.00         1
       26500       0.00      0.00      0.00         1
       26920       0.00      0.00      0.00         0
       26990       0.00      0.00      0.00         1
       27890       0.00      0.00      0.00         1
       27990       0.00      0.00      0.00         2
       28099       0.00      0.00      0.00         0
       28990       0.00      0.00      0.00         0
       29990       0.00      0.00      0.00         1
       29999       0.00      0.00      0.00         0
       30849       0.00      0.00      0.00         0
       31890       0.00      0.00      0.00         0
       31990       0.00      0.00      0.00         3
       32790       0.00      0.00      0.00         0
       32990       0.00      0.00      0.00         0
       32999       0.00      0.00      0.00         1
       33199       0.00      0.00      0.00         0
       33590       0.00      0.00      0.00         0
       33790       0.00      0.00      0.00         1
       33990       0.00      0.00      0.00         3
       34250       0.00      0.00      0.00         1
       34499       0.00      0.00      0.00         0
       34990       0.00      0.00      0.00         0
       34999       0.00      0.00      0.00         1
       35990       0.00      0.00      0.00         3
       35999       0.00      0.00      0.00         1
       36480       0.00      0.00      0.00         0
       36490       0.00      0.00      0.00         0
       36990       0.00      0.00      0.00         3
       36999       0.00      0.00      0.00         0
       37790       0.00      0.00      0.00         0
       37980       0.00      0.00      0.00         1
       37990       0.00      0.00      0.00         5
       38390       0.00      0.00      0.00         0
       38990       0.00      0.00      0.00         3
       39150       0.00      0.00      0.00         1
       39600       0.00      0.00      0.00         1
       39990       0.00      0.00      0.00         6
       40250       0.00      0.00      0.00         0
       40689       0.00      0.00      0.00         0
       40990       0.00      0.00      0.00         0
       41190       0.00      0.00      0.00         0
       41710       0.00      0.00      0.00         0
       42990       0.00      0.00      0.00         1
       43990       0.00      0.00      0.00         1
       44000       0.00      0.00      0.00         1
       44190       0.00      0.00      0.00         0
       44500       0.00      0.00      0.00         0
       44980       0.00      0.00      0.00         1
       44989       0.00      0.00      0.00         0
       44990       0.00      0.00      0.00         3
       45889       0.00      0.00      0.00         1
       45989       0.00      0.00      0.00         1
       45990       0.00      0.00      0.00         0
       45999       0.00      0.00      0.00         0
       46900       0.00      0.00      0.00         1
       47990       0.00      0.00      0.00         2
       48990       0.00      0.00      0.00         1
       48999       0.00      0.00      0.00         1
       49290       0.00      0.00      0.00         1
       49580       0.00      0.00      0.00         1
       49989       0.00      0.00      0.00         1
       49990       0.00      0.00      0.00         4
       50970       0.00      0.00      0.00         0
       50990       0.00      0.00      0.00         2
       51390       0.00      0.00      0.00         0
       51499       0.00      0.00      0.00         0
       51780       0.00      0.00      0.00         0
       51990       0.00      0.00      0.00         4
       51999       0.00      0.00      0.00         0
       52128       0.00      0.00      0.00         0
       52500       0.00      0.00      0.00         1
       52990       0.00      0.00      0.00         1
       53990       0.00      0.00      0.00         2
       54490       0.00      0.00      0.00         1
       54790       0.00      0.00      0.00         1
       54990       0.00      0.00      0.00         1
       55990       0.00      0.00      0.00         1
       56889       0.00      0.00      0.00         1
       56990       0.00      0.00      0.00         4
       57290       0.00      0.00      0.00         1
       57580       0.00      0.00      0.00         0
       57799       0.00      0.00      0.00         0
       57990       0.00      0.00      0.00         3
       58990       0.00      0.00      0.00         1
       59900       0.00      0.00      0.00         1
       59990       0.00      0.00      0.00         1
       60390       0.00      0.00      0.00         0
       60490       0.00      0.00      0.00         1
       60539       0.00      0.00      0.00         0
       60990       0.00      0.00      0.00         2
       61490       0.00      0.00      0.00         1
       61990       0.00      0.00      0.00         4
       62889       0.00      0.00      0.00         0
       62990       0.00      0.00      0.00         0
       63490       0.00      0.00      0.00         0
       63990       0.00      0.00      0.00         0
       64490       0.00      0.00      0.00         0
       64590       0.00      0.00      0.00         1
       64990       0.00      0.00      0.00         2
       65391       0.00      0.00      0.00         1
       65990       0.00      0.00      0.00         1
       66648       0.00      0.00      0.00         0
       66990       0.00      0.00      0.00         0
       67000       0.00      0.00      0.00         0
       67990       0.00      0.00      0.00         2
       67999       0.00      0.00      0.00         1
       68990       0.00      0.00      0.00         0
       69490       0.00      0.00      0.00         0
       71990       0.00      0.00      0.00         1
       72490       0.00      0.00      0.00         1
       72500       0.00      0.00      0.00         0
       72990       0.50      1.00      0.67         1
       72999       0.00      0.00      0.00         1
       73990       0.00      0.00      0.00         0
       74390       0.00      0.00      0.00         1
       74499       0.00      0.00      0.00         1
       74990       0.00      0.00      0.00         1
       77990       0.00      0.00      0.00         2
       78400       0.00      0.00      0.00         0
       79990       0.00      0.00      0.00         2
       79999       0.00      0.00      0.00         0
       80610       0.00      0.00      0.00         0
       80900       0.00      0.00      0.00         1
       82799       0.00      0.00      0.00         0
       83249       0.00      0.00      0.00         1
       83990       0.00      0.00      0.00         0
       84390       0.00      0.00      0.00         1
       84490       0.00      0.00      0.00         1
       84800       0.00      0.00      0.00         1
       84990       0.00      0.00      0.00         1
       85990       0.00      0.00      0.00         1
       86990       0.00      0.00      0.00         0
       87990       0.00      0.00      0.00         1
       88990       0.00      0.00      0.00         0
       89500       0.00      0.00      0.00         1
       89799       0.00      0.00      0.00         1
       89990       0.00      0.00      0.00         3
       89999       0.00      0.00      0.00         0
       90000       0.00      0.00      0.00         1
       93990       0.00      0.00      0.00         1
       94990       0.00      0.00      0.00         1
       97990       0.00      0.00      0.00         1
       98890       0.00      0.00      0.00         0
       98990       0.00      0.00      0.00         1
       99990       0.00      0.00      0.00         0
       99999       0.00      0.00      0.00         0
      103221       0.00      0.00      0.00         1
      104990       0.00      0.00      0.00         2
      106990       0.00      0.00      0.00         1
      107190       0.00      0.00      0.00         1
      107690       0.00      0.00      0.00         0
      107990       0.00      0.00      0.00         1
      108990       0.00      0.00      0.00         0
      109990       1.00      0.50      0.67         2
      109999       0.00      0.00      0.00         0
      111990       0.00      0.00      0.00         1
      112990       0.00      0.00      0.00         1
      114499       0.00      0.00      0.00         0
      114990       0.00      0.00      0.00         1
      115990       0.00      0.00      0.00         1
      116463       0.00      0.00      0.00         1
      117574       0.00      0.00      0.00         1
      119990       0.00      0.00      0.00         0
      121900       0.00      0.00      0.00         1
      123300       0.00      0.00      0.00         0
      125990       0.00      0.00      0.00         1
      126790       0.00      0.00      0.00         1
      129990       0.00      0.00      0.00         1
      129999       0.00      0.00      0.00         1
      133990       0.00      0.00      0.00         1
      138990       0.00      0.00      0.00         0
      139234       0.00      0.00      0.00         0
      149990       0.00      0.00      0.00         1
      153625       0.00      0.00      0.00         1
      154990       0.00      0.00      0.00         1
      159990       0.00      0.00      0.00         1
      165990       0.00      0.00      0.00         1
      166899       0.00      0.00      0.00         1
      172588       0.00      0.00      0.00         0
      179490       0.00      0.00      0.00         0
      179880       0.00      0.00      0.00         1
      179990       0.00      0.00      0.00         0
      188752       0.00      0.00      0.00         1
      189990       0.00      0.00      0.00         0
      199990       0.00      0.00      0.00         1
      201498       0.00      0.00      0.00         1
      209990       0.00      0.00      0.00         2
      229900       0.00      0.00      0.00         0
      240707       0.00      0.00      0.00         0
      256990       0.00      0.00      0.00         0
      260000       0.00      0.00      0.00         0
      278290       0.00      0.00      0.00         0
      281990       0.00      0.00      0.00         1
      286200       0.00      0.00      0.00         0
      290990       0.00      0.00      0.00         1
      297990       0.00      0.00      0.00         1
      303490       0.00      0.00      0.00         0
      304990       0.00      0.00      0.00         1
      323290       0.00      0.00      0.00         0
      390914       0.00      0.00      0.00         1
      419990       0.00      0.00      0.00         0
      420000       0.00      0.00      0.00         1

    accuracy                           0.01       178
   macro avg       0.01      0.01      0.01       178
weighted avg       0.01      0.01      0.01       178

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [169]:
#  MSE
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)

1601599302.9382021

In [170]:
# MSE & MAE
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("Mean_squared_error:-",mean_squared_error(y_test, y_pred))
print("Mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

Mean_squared_error:- 1601599302.9382021
Mean_absolute_error:- 20754.477528089887

In [171]:
rmse=np.sqrt(mean_squared_error(y_test, y_pred))

In [172]:
rmse

np.float64(40019.98629357839)

In [173]:
rmse=np.sqrt(mean_absolute_error(y_test, y_pred))

In [174]:
rmse

np.float64(144.06414379744146)

In [175]:
from sklearn.neighbors import KNeighborsClassifier
knn =KNeighborsClassifier()
knn.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_base.py:501: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)

KNeighborsClassifier()

In [176]:
pred =knn.predict(x_test)

In [177]:
pred

array([ 39965,  15990,  47990,  78990,  28990,  23990,  13990,  51999,
       107690,  60990,  31990,  44500,  51990,  23990,  49990,  46990,
        25490,  10990,  29990,  26732,  31990,  58490,  15990,  23990,
        40789,  35490,  32990,  67000,  48990,  29980,  68990,  70990,
        58490,  25490,  74990,  29990,  39990,  30990,  31890,  79990,
        85590,  23990,  43999,  47990,  21990,  47990,  70990,  48990,
        53649,  74990,  43999,  36990,  48990,  22990,  31990,  47990,
        28099,  25490,  29980,  19990,  13990,  58490,  13990,  87990,
        28990,  24999,  31990,  22990,  51499,  58490,  54990,  18990,
        39990,  46200,  30990,  63990,  62990,  37990,  59990,  68000,
        55500,  60990,  58490,  42999,  58990,  43990, 215994,  37990,
        18990,  18990,  65990,  49990,  22990,  30990,  51499,  18990,
        98890,  94990,  32990,  96990,  18990,  32990,  15990,  98890,
        31500,  79990,  70990,  73990,  62990,  46990,  23990,  85490,
        37790,  74990,  37290,  18990,  31500,  34990,  37990,  60990,
        15990,  23990,  79990,  98890,  49990,  19990,  69990,  48990,
        34990,  59990,  29990,  39965,  29990, 127990,  37990,  31500,
        31490,  46200,  65990,  35490,  70990,  58490,  79990,  35990,
        34990,  19850,  43490,  55500,  54999,  59729,  45990,  45990,
        31990,  60990,  31490,  70990,  59729,  73990,  69990,  48990,
        87990,  26990,  50990,  31990,  32990,  26990,  43990,  31990,
        37990,  59990, 129199,  31490,  58990,  34990,  34990,  62990,
        31500,  47990])

In [178]:
y_test

      price
296   61490
682  149990
535   56990
644   89990
623   87990
..      ...
25    43990
84    38990
10    49990
442   34999
762   44000

[178 rows x 1 columns]

In [179]:
knn.score(x_test, y_test)

0.016853932584269662

In [180]:
knn.score(x_train, y_train)

0.21015514809590974

In [181]:
# without hyper parameter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier()
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [182]:
rfc.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_forest.py:811: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)

RandomForestClassifier()

In [183]:
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

0.02247191011235955
0.8688293370944993

In [184]:
# With hyper paramter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=1, min_samples_split=2)
rfc.fit(x_train, y_train)
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_forest.py:811: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py:289: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)

0.016853932584269662
0.04090267983074753