In [1]:
import pandas as pd
df = pd.read_csv(r"D:\Data Science with AI & ML\SITP-12th-May\PANDAS\loan_approval.csv")
missing_percent = df.isnull().mean() * 100
print("Missing Percentage in Each Column:")
print(missing_percent)
cols_to_remove = missing_percent[missing_percent > 20].index
print("\nColumns to Remove (>20% missing values):")
print(list(cols_to_remove))
df_cleaned = df.drop(columns=cols_to_remove)
print("\nRemaining Columns:")
print(df_cleaned.columns.tolist())

Missing Percentage in Each Column:
name              0.0
city              0.0
income            0.0
credit_score      0.0
loan_amount       0.0
years_employed    0.0
points            0.0
loan_approved     0.0
dtype: float64

Columns to Remove (>20% missing values):
[]

Remaining Columns:
['name', 'city', 'income', 'credit_score', 'loan_amount', 'years_employed', 'points', 'loan_approved']

In [2]:
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [3]:
df.tail()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False